### PR TITLE
0.12.5

### LINKED ISSUE #59: Expand paths for attribute-style access
It looks like path expansion only happens for key-like access syntax; it should work for both access patterns.

### PR DESCRIPTION
**Pull request by vreuter**
Close #59

### CODE REVIEW

**Comment by nsheff** [comment]
if we do https://github.com/databio/lucidoc/pull/35 first we'll get nicer docs on this release.

**Comment by vreuter** [comment]
So although nothing about `lucidoc` is declared here, you've set up the buid in such a way that it will use the latest version?

**Comment by nsheff** [comment]
that's just the way RTD works. it builds from pypi on each build and will automatically grab the latest.

**Comment by vreuter** [comment]
> that's just the way RTD works. it builds from pypi on each build and will automatically grab the latest.

sweet that's awesome

**Pull request merged**
